version: '3'

services:
  app:
    image: 'bolshakovmi/movie_assistant:1.0.1'
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/movie_helper
      - SPRING_DATASOURCE_USERNAME=movie_helper_admin
      - SPRING_DATASOURCE_PASSWORD=movie_helper_password

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=movie_helper_admin
      - POSTGRES_PASSWORD=movie_helper_password
      - POSTGRES_DB=movie_helper
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: